---
default_stages: [commit]
files: 'tf-modules/*'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
      files: '.pre-commit-config.yaml'
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs